### ISSUE TITLE
Error on bin/init-neo4j.sh while changing neo4j default password with curl

### ISSUE THREAD

**Issue by sepe81** [jdinkla/codingdavinci-familiennamen#1]
I get an error under Ubuntu 16.04. and "Docker version 1.12.3, build 6b644ec" while changing the neo4j default password.

Console log:
```
curl: (56) Recv failure: Die Verbindung wurde vom Kommunikationspartner zurückgesetzt
```

IMO `localhost` should be changed to `0.0.0.0` in the following section to get a valid curl connection within the container. 

```
# change password echo "Sleep until database is constructed ... "
sleep 5
curl -X POST http://neo4j:neo4j@localhost:7474/user/neo4j/password -d 'password=gra91PH'
```

Afterwards it "works on my machine". ;-)

Thanks for the very interesting project.

**Comment by jdinkla** [comment]
Thanks for the bug report. I'll look into this ASAP.

**Comment by jdinkla** [comment]
I fixed it today. Thanks again.
